library(MASS)
library(fitdistrplus)
library(magrittr)
library(simmer)
library(simmer.plot)
library(dplyr)
library(lazyeval)
library(parallel)
library(e1071)
library(plotly)
library(ggplot2)
library(triangle)

library(sqldf)
library(knitr)
library(rmarkdown)